# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main/resume

pool:
  vmImage: windows-latest

steps:
- task: AzureFileCopy@5
  inputs:
    SourcePath: '${Build.Repository.LocalPath}/resume/*'
    azureSubscription: 'Azure Sub1 Filecopy'
    Destination: 'AzureBlob'
    storage: 'sttwcus0cloudresume1'
    ContainerName: '$web'
    CleanTargetBeforeCopy: true

- pwsh: az devops configure --defaults organization='$(System.TeamFoundationCollectionUri)' project='$(System.TeamProject)' --use-git-aliases true
  displayName: 'Set default Azure DevOps organization and project'

- pwsh: |
    az cdn endpoint purge --resource-group 'rgtwcus0cloudresume1' --profile-name 'cdntwcus0cloudresume1' --name 'cdneptwcus0cloudresume1' --no-wait --content-paths /*

  displayName: 'Purge CDN endpoint'
  env:
    AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)