# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main/resume

pool:
  vmImage: windows-latest

steps:
- task: AzureFileCopy@5
  inputs:
    SourcePath: '/resume'
    azureSubscription: 'Azure Sub1 Filecopy'
    Destination: 'AzureBlob'
    storage: 'sttwcus0cloudresume1'
    ContainerName: '$web'
    CleanTargetBeforeCopy: true